### ISSUE TITLE
Does it include runoff due to snowment?

### ISSUE THREAD

**Issue by LSRathore** [UW-Hydro/VIC_Routing#3]
The fortran code of make_covolution uses runoff and baseflow to compute the discharge at outlet. What if there is snowment in the area?
Does the runoff computed by vic consists of surface runoff and snow melt?
If not then, snow melt component should also be added while computing the discharge at the outlet.

**Comment by jhamman** [comment]
Yes, VIC's runoff / baseflow variables include contributions from snowmelt.
